Order Date: [wcj_order_date]
Order Nr.: [wcj_order_number]
Buyer: [wcj_order_billing_address]
Total (excl. TAX): [wcj_order_total_excl_tax]
Taxes: [wcj_order_total_tax hide_if_zero="no"]
Order Total: [wcj_order_total]
Payment method: [wcj_order_payment_method]