<?php
/**
 * WooCommerce Jetpack Functions
 *
 * The WooCommerce Jetpack Functions.
 *
 * @version 2.4.3
 * @author  Algoritmika Ltd.
 */

return array(
	array( 'code' => 'AFN', 'name' => __( 'Afghan afghani', 'woocommerce-jetpack' ),                             'symbol' => 'AFN', ),
	array( 'code' => 'ALL', 'name' => __( 'Albanian lek', 'woocommerce-jetpack' ),                               'symbol' => 'ALL', ),
	array( 'code' => 'DZD', 'name' => __( 'Algerian dinar', 'woocommerce-jetpack' ),                             'symbol' => 'DZD', ),
	array( 'code' => 'AOA', 'name' => __( 'Angolan kwanza', 'woocommerce-jetpack' ),                             'symbol' => 'AOA', ),
	array( 'code' => 'ARS', 'name' => __( 'Argentine peso', 'woocommerce-jetpack' ),                             'symbol' => 'ARS', ),
	array( 'code' => 'AMD', 'name' => __( 'Armenian dram', 'woocommerce-jetpack' ),                              'symbol' => 'AMD', ),
	array( 'code' => 'AWG', 'name' => __( 'Aruban florin', 'woocommerce-jetpack' ),                              'symbol' => 'AWG', ),
	array( 'code' => 'AUD', 'name' => __( 'Australian dollar', 'woocommerce-jetpack' ),                          'symbol' => '&#36;', ),
	array( 'code' => 'AZN', 'name' => __( 'Azerbaijani manat', 'woocommerce-jetpack' ),                          'symbol' => 'AZN', ),
	array( 'code' => 'BSD', 'name' => __( 'Bahamian dollar', 'woocommerce-jetpack' ),                            'symbol' => 'BSD', ),
	array( 'code' => 'BHD', 'name' => __( 'Bahraini dinar', 'woocommerce-jetpack' ),                             'symbol' => 'BHD', ),
	array( 'code' => 'BDT', 'name' => __( 'Bangladeshi taka', 'woocommerce-jetpack' ),                           'symbol' => 'BDT', ),
	array( 'code' => 'BBD', 'name' => __( 'Barbadian dollar', 'woocommerce-jetpack' ),                           'symbol' => 'BBD', ),
	array( 'code' => 'BYR', 'name' => __( 'Belarusian ruble', 'woocommerce-jetpack' ),                           'symbol' => 'BYR', ),
	array( 'code' => 'BZD', 'name' => __( 'Belize dollar', 'woocommerce-jetpack' ),                              'symbol' => 'BZD', ),
	array( 'code' => 'BTN', 'name' => __( 'Bhutanese ngultrum', 'woocommerce-jetpack' ),                         'symbol' => 'BTN', ),
	array( 'code' => 'BOB', 'name' => __( 'Bolivian boliviano', 'woocommerce-jetpack' ),                         'symbol' => 'BOB', ),
	array( 'code' => 'BAM', 'name' => __( 'Bosnia and Herzegovina konvertibilna marka', 'woocommerce-jetpack' ), 'symbol' => 'BAM', ),
	array( 'code' => 'BWP', 'name' => __( 'Botswana pula', 'woocommerce-jetpack' ),                              'symbol' => 'BWP', ),
	array( 'code' => 'BRL', 'name' => __( 'Brazilian real', 'woocommerce-jetpack' ),                             'symbol' => '&#82;&#36;', ),
	array( 'code' => 'GBP', 'name' => __( 'British pound', 'woocommerce-jetpack' ),                              'symbol' => '&pound;', ),
	array( 'code' => 'BND', 'name' => __( 'Brunei dollar', 'woocommerce-jetpack' ),                              'symbol' => 'BND', ),
	array( 'code' => 'BGN', 'name' => __( 'Bulgarian lev', 'woocommerce-jetpack' ),                              'symbol' => 'BGN', ),
	array( 'code' => 'BIF', 'name' => __( 'Burundi franc', 'woocommerce-jetpack' ),                              'symbol' => 'BIF', ),
	array( 'code' => 'KYD', 'name' => __( 'Cayman Islands dollar', 'woocommerce-jetpack' ),                      'symbol' => 'KYD', ),
	array( 'code' => 'KHR', 'name' => __( 'Cambodian riel', 'woocommerce-jetpack' ),                             'symbol' => 'KHR', ),
	array( 'code' => 'CAD', 'name' => __( 'Canadian dollar', 'woocommerce-jetpack' ),                            'symbol' => 'CAD', ),
	array( 'code' => 'CVE', 'name' => __( 'Cape Verdean escudo', 'woocommerce-jetpack' ),                        'symbol' => 'CVE', ),
	array( 'code' => 'XAF', 'name' => __( 'Central African CFA franc', 'woocommerce-jetpack' ),                  'symbol' => 'XAF', ),
	array( 'code' => 'GQE', 'name' => __( 'Central African CFA franc', 'woocommerce-jetpack' ),                  'symbol' => 'GQE', ),
	array( 'code' => 'XPF', 'name' => __( 'CFP franc', 'woocommerce-jetpack' ),                                  'symbol' => 'XPF', ),
	array( 'code' => 'CLP', 'name' => __( 'Chilean peso', 'woocommerce-jetpack' ),                               'symbol' => 'CLP', ),
	array( 'code' => 'CNY', 'name' => __( 'Chinese renminbi', 'woocommerce-jetpack' ),                           'symbol' => '&yen;', ),
	array( 'code' => 'COP', 'name' => __( 'Colombian peso', 'woocommerce-jetpack' ),                             'symbol' => 'COP', ),
	array( 'code' => 'KMF', 'name' => __( 'Comorian franc', 'woocommerce-jetpack' ),                             'symbol' => 'KMF', ),
	array( 'code' => 'CDF', 'name' => __( 'Congolese franc', 'woocommerce-jetpack' ),                            'symbol' => 'CDF', ),
	array( 'code' => 'CRC', 'name' => __( 'Costa Rican colon', 'woocommerce-jetpack' ),                          'symbol' => 'CRC', ),
	array( 'code' => 'HRK', 'name' => __( 'Croatian kuna', 'woocommerce-jetpack' ),                              'symbol' => 'HRK', ),
	array( 'code' => 'CUC', 'name' => __( 'Cuban peso', 'woocommerce-jetpack' ),                                 'symbol' => 'CUC', ),
	array( 'code' => 'CZK', 'name' => __( 'Czech koruna', 'woocommerce-jetpack' ),                               'symbol' => '&#75;&#269;', ),
	array( 'code' => 'DKK', 'name' => __( 'Danish krone', 'woocommerce-jetpack' ),                               'symbol' => '&#107;&#114;', ),
	array( 'code' => 'DJF', 'name' => __( 'Djiboutian franc', 'woocommerce-jetpack' ),                           'symbol' => 'DJF', ),
	array( 'code' => 'DOP', 'name' => __( 'Dominican peso', 'woocommerce-jetpack' ),                             'symbol' => 'DOP', ),
	array( 'code' => 'XCD', 'name' => __( 'East Caribbean dollar', 'woocommerce-jetpack' ),                      'symbol' => 'XCD', ),
	array( 'code' => 'EGP', 'name' => __( 'Egyptian pound', 'woocommerce-jetpack' ),                             'symbol' => 'EGP', ),
	array( 'code' => 'ERN', 'name' => __( 'Eritrean nakfa', 'woocommerce-jetpack' ),                             'symbol' => 'ERN', ),
	array( 'code' => 'EEK', 'name' => __( 'Estonian kroon', 'woocommerce-jetpack' ),                             'symbol' => 'EEK', ),
	array( 'code' => 'ETB', 'name' => __( 'Ethiopian birr', 'woocommerce-jetpack' ),                             'symbol' => 'ETB', ),
	array( 'code' => 'EUR', 'name' => __( 'European euro', 'woocommerce-jetpack' ),                              'symbol' => '&euro;', ),
	array( 'code' => 'FKP', 'name' => __( 'Falkland Islands pound', 'woocommerce-jetpack' ),                     'symbol' => 'FKP', ),
	array( 'code' => 'FJD', 'name' => __( 'Fijian dollar', 'woocommerce-jetpack' ),                              'symbol' => 'FJD', ),
	array( 'code' => 'GMD', 'name' => __( 'Gambian dalasi', 'woocommerce-jetpack' ),                             'symbol' => 'GMD', ),
	array( 'code' => 'GEL', 'name' => __( 'Georgian lari', 'woocommerce-jetpack' ),                              'symbol' => 'GEL', ),
	array( 'code' => 'GHS', 'name' => __( 'Ghanaian cedi', 'woocommerce-jetpack' ),                              'symbol' => 'GHS', ),
	array( 'code' => 'GIP', 'name' => __( 'Gibraltar pound', 'woocommerce-jetpack' ),                            'symbol' => 'GIP', ),
	array( 'code' => 'GTQ', 'name' => __( 'Guatemalan quetzal', 'woocommerce-jetpack' ),                         'symbol' => 'GTQ', ),
	array( 'code' => 'GNF', 'name' => __( 'Guinean franc', 'woocommerce-jetpack' ),                              'symbol' => 'GNF', ),
	array( 'code' => 'GYD', 'name' => __( 'Guyanese dollar', 'woocommerce-jetpack' ),                            'symbol' => 'GYD', ),
	array( 'code' => 'HTG', 'name' => __( 'Haitian gourde', 'woocommerce-jetpack' ),                             'symbol' => 'HTG', ),
	array( 'code' => 'HNL', 'name' => __( 'Honduran lempira', 'woocommerce-jetpack' ),                           'symbol' => 'HNL', ),
	array( 'code' => 'HKD', 'name' => __( 'Hong Kong dollar', 'woocommerce-jetpack' ),                           'symbol' => '&#36;', ),
	array( 'code' => 'HUF', 'name' => __( 'Hungarian forint', 'woocommerce-jetpack' ),                           'symbol' => '&#70;&#116;', ),
	array( 'code' => 'ISK', 'name' => __( 'Icelandic krona', 'woocommerce-jetpack' ),                            'symbol' => 'ISK', ),
	array( 'code' => 'INR', 'name' => __( 'Indian rupee', 'woocommerce-jetpack' ),                               'symbol' => '&#8377;', ),
	array( 'code' => 'IDR', 'name' => __( 'Indonesian rupiah', 'woocommerce-jetpack' ),                          'symbol' => 'Rp', ),
	array( 'code' => 'IRR', 'name' => __( 'Iranian rial', 'woocommerce-jetpack' ),                               'symbol' => 'IRR', ),
	array( 'code' => 'IQD', 'name' => __( 'Iraqi dinar', 'woocommerce-jetpack' ),                                'symbol' => 'IQD', ),
	array( 'code' => 'ILS', 'name' => __( 'Israeli new sheqel', 'woocommerce-jetpack' ),                         'symbol' => '&#8362;', ),
	array( 'code' => 'YER', 'name' => __( 'Yemeni rial', 'woocommerce-jetpack' ),                                'symbol' => 'YER', ),
	array( 'code' => 'JMD', 'name' => __( 'Jamaican dollar', 'woocommerce-jetpack' ),                            'symbol' => 'JMD', ),
	array( 'code' => 'JPY', 'name' => __( 'Japanese yen', 'woocommerce-jetpack' ),                               'symbol' => '&yen;', ),
	array( 'code' => 'JOD', 'name' => __( 'Jordanian dinar', 'woocommerce-jetpack' ),                            'symbol' => 'JOD', ),
	array( 'code' => 'KZT', 'name' => __( 'Kazakhstani tenge', 'woocommerce-jetpack' ),                          'symbol' => 'KZT', ),
	array( 'code' => 'KES', 'name' => __( 'Kenyan shilling', 'woocommerce-jetpack' ),                            'symbol' => 'KES', ),
	array( 'code' => 'KGS', 'name' => __( 'Kyrgyzstani som', 'woocommerce-jetpack' ),                            'symbol' => 'KGS', ),
	array( 'code' => 'KWD', 'name' => __( 'Kuwaiti dinar', 'woocommerce-jetpack' ),                              'symbol' => 'KWD', ),
	array( 'code' => 'LAK', 'name' => __( 'Lao kip', 'woocommerce-jetpack' ),                                    'symbol' => 'LAK', ),
//	array( 'code' => 'KIP', 'name' => __( 'Lao kip', 'woocommerce-jetpack' ),                                    'symbol' => 'KIP', ),
	array( 'code' => 'LVL', 'name' => __( 'Latvian lats', 'woocommerce-jetpack' ),                               'symbol' => 'LVL', ),
	array( 'code' => 'LBP', 'name' => __( 'Lebanese lira', 'woocommerce-jetpack' ),                              'symbol' => 'LBP', ),
	array( 'code' => 'LSL', 'name' => __( 'Lesotho loti', 'woocommerce-jetpack' ),                               'symbol' => 'LSL', ),
	array( 'code' => 'LRD', 'name' => __( 'Liberian dollar', 'woocommerce-jetpack' ),                            'symbol' => 'LRD', ),
	array( 'code' => 'LYD', 'name' => __( 'Libyan dinar', 'woocommerce-jetpack' ),                               'symbol' => 'LYD', ),
	array( 'code' => 'LTL', 'name' => __( 'Lithuanian litas', 'woocommerce-jetpack' ),                           'symbol' => 'LTL', ),
	array( 'code' => 'MOP', 'name' => __( 'Macanese pataca', 'woocommerce-jetpack' ),                            'symbol' => 'MOP', ),
	array( 'code' => 'MKD', 'name' => __( 'Macedonian denar', 'woocommerce-jetpack' ),                           'symbol' => 'MKD', ),
	array( 'code' => 'MGA', 'name' => __( 'Malagasy ariary', 'woocommerce-jetpack' ),                            'symbol' => 'MGA', ),
	array( 'code' => 'MYR', 'name' => __( 'Malaysian ringgit', 'woocommerce-jetpack' ),                          'symbol' => '&#82;&#77;', ),
	array( 'code' => 'MWK', 'name' => __( 'Malawian kwacha', 'woocommerce-jetpack' ),                            'symbol' => 'MWK', ),
	array( 'code' => 'MVR', 'name' => __( 'Maldivian rufiyaa', 'woocommerce-jetpack' ),                          'symbol' => 'MVR', ),
	array( 'code' => 'MRO', 'name' => __( 'Mauritanian ouguiya', 'woocommerce-jetpack' ),                        'symbol' => 'MRO', ),
	array( 'code' => 'MUR', 'name' => __( 'Mauritian rupee', 'woocommerce-jetpack' ),                            'symbol' => 'MUR', ),
	array( 'code' => 'MXN', 'name' => __( 'Mexican peso', 'woocommerce-jetpack' ),                               'symbol' => '&#36;', ),
	array( 'code' => 'MMK', 'name' => __( 'Myanma kyat', 'woocommerce-jetpack' ),                                'symbol' => 'MMK', ),
	array( 'code' => 'MDL', 'name' => __( 'Moldovan leu', 'woocommerce-jetpack' ),                               'symbol' => 'MDL', ),
	array( 'code' => 'MNT', 'name' => __( 'Mongolian tugrik', 'woocommerce-jetpack' ),                           'symbol' => 'MNT', ),
	array( 'code' => 'MAD', 'name' => __( 'Moroccan dirham', 'woocommerce-jetpack' ),                            'symbol' => 'MAD', ),
	array( 'code' => 'MZM', 'name' => __( 'Mozambican metical', 'woocommerce-jetpack' ),                         'symbol' => 'MZM', ),
	array( 'code' => 'NAD', 'name' => __( 'Namibian dollar', 'woocommerce-jetpack' ),                            'symbol' => 'NAD', ),
	array( 'code' => 'NPR', 'name' => __( 'Nepalese rupee', 'woocommerce-jetpack' ),                             'symbol' => 'NPR', ),
	array( 'code' => 'ANG', 'name' => __( 'Netherlands Antillean gulden', 'woocommerce-jetpack' ),               'symbol' => 'ANG', ),
	array( 'code' => 'TWD', 'name' => __( 'New Taiwan dollar', 'woocommerce-jetpack' ),                          'symbol' => '&#78;&#84;&#36;', ),
	array( 'code' => 'NZD', 'name' => __( 'New Zealand dollar', 'woocommerce-jetpack' ),                         'symbol' => '&#36;', ),
	array( 'code' => 'NIO', 'name' => __( 'Nicaraguan cordoba', 'woocommerce-jetpack' ),                         'symbol' => 'NIO', ),
	array( 'code' => 'NGN', 'name' => __( 'Nigerian naira', 'woocommerce-jetpack' ),                             'symbol' => 'NGN', ),
	array( 'code' => 'KPW', 'name' => __( 'North Korean won', 'woocommerce-jetpack' ),                           'symbol' => 'KPW', ),
	array( 'code' => 'NOK', 'name' => __( 'Norwegian krone', 'woocommerce-jetpack' ),                            'symbol' => '&#107;&#114;', ),
	array( 'code' => 'OMR', 'name' => __( 'Omani rial', 'woocommerce-jetpack' ),                                 'symbol' => 'OMR', ),
	array( 'code' => 'TOP', 'name' => __( 'Paanga', 'woocommerce-jetpack' ),                                     'symbol' => 'TOP', ),
	array( 'code' => 'PKR', 'name' => __( 'Pakistani rupee', 'woocommerce-jetpack' ),                            'symbol' => 'PKR', ),
	array( 'code' => 'PAB', 'name' => __( 'Panamanian balboa', 'woocommerce-jetpack' ),                          'symbol' => 'PAB', ),
	array( 'code' => 'PGK', 'name' => __( 'Papua New Guinean kina', 'woocommerce-jetpack' ),                     'symbol' => 'PGK', ),
	array( 'code' => 'PYG', 'name' => __( 'Paraguayan guarani', 'woocommerce-jetpack' ),                         'symbol' => 'PYG', ),
	array( 'code' => 'PEN', 'name' => __( 'Peruvian nuevo sol', 'woocommerce-jetpack' ),                         'symbol' => 'PEN', ),
	array( 'code' => 'PHP', 'name' => __( 'Philippine peso', 'woocommerce-jetpack' ),                            'symbol' => '&#8369;', ),
	array( 'code' => 'PLN', 'name' => __( 'Polish zloty', 'woocommerce-jetpack' ),                               'symbol' => '&#122;&#322;', ),
	array( 'code' => 'QAR', 'name' => __( 'Qatari riyal', 'woocommerce-jetpack' ),                               'symbol' => 'QAR', ),
	array( 'code' => 'RON', 'name' => __( 'Romanian leu', 'woocommerce-jetpack' ),                               'symbol' => 'lei', ),
	array( 'code' => 'RUB', 'name' => __( 'Russian ruble', 'woocommerce-jetpack' ),                              'symbol' => 'RUB', ),
	array( 'code' => 'RWF', 'name' => __( 'Rwandan franc', 'woocommerce-jetpack' ),                              'symbol' => 'RWF', ),
	array( 'code' => 'SHP', 'name' => __( 'Saint Helena pound', 'woocommerce-jetpack' ),                         'symbol' => 'SHP', ),
	array( 'code' => 'WST', 'name' => __( 'Samoan tala', 'woocommerce-jetpack' ),                                'symbol' => 'WST', ),
	array( 'code' => 'STD', 'name' => __( 'Sao Tome and Principe dobra', 'woocommerce-jetpack' ),                'symbol' => 'STD', ),
	array( 'code' => 'SAR', 'name' => __( 'Saudi riyal', 'woocommerce-jetpack' ),                                'symbol' => 'SAR', ),
	array( 'code' => 'SCR', 'name' => __( 'Seychellois rupee', 'woocommerce-jetpack' ),                          'symbol' => 'SCR', ),
	array( 'code' => 'RSD', 'name' => __( 'Serbian dinar', 'woocommerce-jetpack' ),                              'symbol' => 'RSD', ),
	array( 'code' => 'SLL', 'name' => __( 'Sierra Leonean leone', 'woocommerce-jetpack' ),                       'symbol' => 'SLL', ),
	array( 'code' => 'SGD', 'name' => __( 'Singapore dollar', 'woocommerce-jetpack' ),                           'symbol' => '&#36;', ),
	array( 'code' => 'SYP', 'name' => __( 'Syrian pound', 'woocommerce-jetpack' ),                               'symbol' => 'SYP', ),
	array( 'code' => 'SKK', 'name' => __( 'Slovak koruna', 'woocommerce-jetpack' ),                              'symbol' => 'SKK', ),
	array( 'code' => 'SBD', 'name' => __( 'Solomon Islands dollar', 'woocommerce-jetpack' ),                     'symbol' => 'SBD', ),
	array( 'code' => 'SOS', 'name' => __( 'Somali shilling', 'woocommerce-jetpack' ),                            'symbol' => 'SOS', ),
	array( 'code' => 'ZAR', 'name' => __( 'South African rand', 'woocommerce-jetpack' ),                         'symbol' => '&#82;', ),
	array( 'code' => 'KRW', 'name' => __( 'South Korean won', 'woocommerce-jetpack' ),                           'symbol' => '&#8361;', ),
	array( 'code' => 'XDR', 'name' => __( 'Special Drawing Rights', 'woocommerce-jetpack' ),                     'symbol' => 'XDR', ),
	array( 'code' => 'LKR', 'name' => __( 'Sri Lankan rupee', 'woocommerce-jetpack' ),                           'symbol' => 'LKR', ),
	array( 'code' => 'SDG', 'name' => __( 'Sudanese pound', 'woocommerce-jetpack' ),                             'symbol' => 'SDG', ),
	array( 'code' => 'SRD', 'name' => __( 'Surinamese dollar', 'woocommerce-jetpack' ),                          'symbol' => 'SRD', ),
	array( 'code' => 'SZL', 'name' => __( 'Swazi lilangeni', 'woocommerce-jetpack' ),                            'symbol' => 'SZL', ),
	array( 'code' => 'SEK', 'name' => __( 'Swedish krona', 'woocommerce-jetpack' ),                              'symbol' => '&#107;&#114;', ),
	array( 'code' => 'CHF', 'name' => __( 'Swiss franc', 'woocommerce-jetpack' ),                                'symbol' => '&#67;&#72;&#70;', ),
	array( 'code' => 'TJS', 'name' => __( 'Tajikistani somoni', 'woocommerce-jetpack' ),                         'symbol' => 'TJS', ),
	array( 'code' => 'TZS', 'name' => __( 'Tanzanian shilling', 'woocommerce-jetpack' ),                         'symbol' => 'TZS', ),
	array( 'code' => 'THB', 'name' => __( 'Thai baht', 'woocommerce-jetpack' ),                                  'symbol' => '&#3647;', ),
	array( 'code' => 'TTD', 'name' => __( 'Trinidad and Tobago dollar', 'woocommerce-jetpack' ),                 'symbol' => 'TTD', ),
	array( 'code' => 'TND', 'name' => __( 'Tunisian dinar', 'woocommerce-jetpack' ),                             'symbol' => 'TND', ),
	array( 'code' => 'TRY', 'name' => __( 'Turkish new lira', 'woocommerce-jetpack' ),                           'symbol' => '&#84;&#76;', ),
	array( 'code' => 'TMM', 'name' => __( 'Turkmen manat', 'woocommerce-jetpack' ),                              'symbol' => 'TMM', ),
	array( 'code' => 'AED', 'name' => __( 'UAE dirham', 'woocommerce-jetpack' ),                                 'symbol' => 'AED', ),
	array( 'code' => 'UGX', 'name' => __( 'Ugandan shilling', 'woocommerce-jetpack' ),                           'symbol' => 'UGX', ),
	array( 'code' => 'UAH', 'name' => __( 'Ukrainian hryvnia', 'woocommerce-jetpack' ),                          'symbol' => 'UAH', ),
	array( 'code' => 'USD', 'name' => __( 'United States dollar', 'woocommerce-jetpack' ),                       'symbol' => '&#36;', ),
	array( 'code' => 'UYU', 'name' => __( 'Uruguayan peso', 'woocommerce-jetpack' ),                             'symbol' => 'UYU', ),
	array( 'code' => 'UZS', 'name' => __( 'Uzbekistani som', 'woocommerce-jetpack' ),                            'symbol' => 'UZS', ),
	array( 'code' => 'VUV', 'name' => __( 'Vanuatu vatu', 'woocommerce-jetpack' ),                               'symbol' => 'VUV', ),
	array( 'code' => 'VEF', 'name' => __( 'Venezuelan bolivar', 'woocommerce-jetpack' ),                         'symbol' => 'VEF', ),
	array( 'code' => 'VND', 'name' => __( 'Vietnamese dong', 'woocommerce-jetpack' ),                            'symbol' => 'VND', ),
	array( 'code' => 'XOF', 'name' => __( 'West African CFA franc', 'woocommerce-jetpack' ),                     'symbol' => 'XOF', ),
	array( 'code' => 'ZMK', 'name' => __( 'Zambian kwacha', 'woocommerce-jetpack' ),                             'symbol' => 'ZMK', ),
	array( 'code' => 'ZWD', 'name' => __( 'Zimbabwean dollar', 'woocommerce-jetpack' ),                          'symbol' => 'ZWD', ),
	array( 'code' => 'RMB', 'name' => __( 'Chinese Yuan', 'woocommerce-jetpack' ),                               'symbol' => '&yen;', ),
);
